name: Release shellb

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_branch
    - name: Create binary
      run: |
        chmod +x install.sh && ./install.sh
        chmod +x build/shellb && cp build/shellb /tmp/shellb

    - name: Create Release
      uses: actions/create-release@latest
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ steps.extract_branch.outputs.branch }}
        tag_name: ${{ github.ref }}

    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/shellb
        asset_name: shellb
        asset_content_type: text/x-shellscript
